demo/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("manager/", include("django_pasttrec_manager.urls", namespace="django_pasttrec_manager")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

django_pasttrec_manager/urls.py
from django.urls import path, re_path
from .views import views, wizards

app_name = "passtrec_trb3setup"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("cards", views.CardsView.as_view(), name="cards"),
    path("card/<int:pk>", views.CardView.as_view(), name="card"),
    path(
        "configuration/<int:pk>",
        views.AsicConfigurationView.as_view(),
        name="configuration",
    ),
    path(
        "calibration/<int:id>", views.CardCalibrationView.as_view(), name="calibration"
    ),
    path("cards_setup/add", views.add_cards_setup_view, name="add_cards_setup"),
    path("cards_setup/<int:pk>", views.CardsSetupView.as_view(), name="cards_setup"),
    path(
        "import/calibrations/wizard",
        wizards.CalibrationsImportWizardView.as_view(),
        name="import_calibrations_wizard",
    ),
    path(
        "import/cards_setups/wizard",
        wizards.CardsSetupsImportWizardView.as_view(),
        name="import_cards_setups_wizard",
    ),
    path(
        "import/cards_setups/<int:pk>/wizard",
        wizards.CardsSetupsImportWizardView.as_view(),
        name="import_cards_setups_wizard",
    ),

    path(
        "export/calibration/wizard",
        wizards.CalibrationExportWizardView.as_view(),
        name="export_calibration_wizard",
    ),

    # path("card/import/insert", card.import_card_insert_view, name="import_card_insert"),
    # path("card/insert/<str:febid>/<str:name>", card.insert_card_view, name="insert_card"),
    # path("card/insert", card.insert_card_view, name="insert_card"),
    # path("card/multiple/<str:names>", card.insert_cards_view, name="insert_cards"),
    # path("card/multiple", card.insert_cards_view, name="insert_cards"),
    # path("card/settings", card.add_settings_view, name="add_settings"),
    # path("card/settings/card/<int:card_pk>", card.add_settings_view, name="add_settings_by_card"),
    # path("card/settings/<int:card>", card.add_settings_view, name="add_settings_by_revision"),
    # path("card/settings/<int:card_pk>/<int:rev_pk>", card.add_settings_view, name="add_settings"),
    # path("card/settings/change/<int:pk>", card.change_settings_view, name="change_settings"),
    # path("card/settings/mass/<int:rev>", card.change_settings_mass_view, name="change_settings_mass"),
    # path("card/settings/delete/<int:card_pk>", card.delete_settings_view, name="delete_card_settings"),
    # path("export/json/<int:pk>", exports.export_json_view, name="export_json"),
    # path("export/shell/<int:pk>", exports.export_shell_view, name="export_shell"),
    # path("import/select/<int:setup>", exports.import_select_view, name="import_select_revision"),
    # path("import/insert/<int:setup>", exports.import_insert_view, name="import_insert_revision"),
    # path("import/file/<int:rev>", exports.import_file_view, name="import_file"),
    # path("import/<int:rev>", exports.import_json_view, name="import_json"),
]

django_pasttrec_manager/models/cards_setup.py
from django.db import models

from . import Card


class CardsSetup(models.Model):
    name = models.CharField(max_length=16)
    cards = models.ManyToManyField(Card)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

django_pasttrec_manager/forms/asics.py
from django import forms
from django.core.validators import FileExtensionValidator
from django.forms import formset_factory

from django_pasttrec_manager.models import AsicConfiguration, AsicBaselineSettings
from django_pasttrec_manager.tools import disable_form_fields


class AsicConfigurationForm(forms.ModelForm):
    template_name = "django_pasttrec_manager/forms/asic_configuration_form.html"

    class Meta:
        model = AsicConfiguration
        fields = "__all__"
        widgets = {
            "notes": forms.Textarea(attrs={"rows": 2, "cols": "auto"}),
        }

    def __init__(self, *args, **kwargs):
        self.insert_new = kwargs.pop("insert_new", None)
        disabled_fields = kwargs.pop("disabled_fields", None)
        enabled_fields = kwargs.pop("enabled_fields", None)
        super().__init__(*args, **kwargs)
        if disabled_fields or enabled_fields:
            disable_form_fields(self, disabled_fields, enabled_fields)


AsicConfigurationFormSet = formset_factory(AsicConfigurationForm, extra=0)


class AsicBaselineSettingsForm(forms.ModelForm):
    template_name = "django_pasttrec_manager/forms/asic_baseline_minimal_form.html"

    def __init__(self, *args, **kwargs):
        self.asic_no = kwargs.pop("asic_no", None)
        self.insert_new = kwargs.pop("insert_new", None)
        super().__init__(*args, **kwargs)

    class Meta:
        model = AsicBaselineSettings
        fields = "__all__"


AsicBaselineSettingsFormSet = formset_factory(AsicBaselineSettingsForm, extra=0)


class AsicSettingsMassChangeForm(forms.Form):
    threshold = forms.IntegerField(min_value=0, max_value=31, required=False)
    tc1c = forms.IntegerField(min_value=0, max_value=3, required=False)
    tc1r = forms.IntegerField(min_value=0, max_value=3, required=False)
    tc2c = forms.IntegerField(min_value=0, max_value=3, required=False)
    tc2r = forms.IntegerField(min_value=0, max_value=3, required=False)

django_pasttrec_manager/forms/exports.py
from django import forms

from django_pasttrec_manager.models import AsicConfiguration, CardsSetup
from django_pasttrec_manager.tools import disable_form_fields

from . import AsicBaselineSettingsForm, AsicConfigurationForm, CardForm

class SetupAndConfigurationForExportCalibration(forms.Form):
    configuration = forms.ChoiceField(
        choices=(lambda setup_objs: [(obj.pk, obj) for obj in setup_objs])(
            AsicConfiguration.objects.all()
        ),
    )

    setup = forms.ChoiceField(
        choices=[(-1, "--- All available cards ---")]
        + [(obj.pk, obj) for obj in CardsSetup.objects.all()],
    )


class SelectCardsForExportCalibration(forms.Form):
    """
    Provides overview of the FEB card, setup and baseline settings for given calibration.
    It presents the previous and next baseline values, and has an check box to mark the
    calibration for overwritting.
    """

    template_name = "django_pasttrec_manager/forms/cards_setup_actions_form.html"

    confirm_actions = forms.BooleanField(
        label="Add to setups",
        required=False,
        initial=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        card_obj_id = kwargs.get("initial")
        print(card_obj_id)

        def update_widgets(name, form, template=None, extras=None):
            if extras is None:
                extras = {}

            new_form = form(prefix=self.prefix, initial=card_obj_id, **extras)
            if template:
                new_form.template_name = template
            setattr(self, f"{name}_form", new_form)
            return new_form

        f = update_widgets(
            "card",
            CardForm,
            # "django_pasttrec_manager/forms/card_form_view.html",
        )

        disable_form_fields(f, enabled_fields=())

django_pasttrec_manager/forms/tools.py
from django import forms
from django.core.exceptions import ValidationError


class JsonUploadFileForm(forms.Form):
    @staticmethod
    def validate_file_extension(value):
        if not value.name.endswith(".json"):
            raise ValidationError("Must be json file")

    file = forms.FileField(validators=[validate_file_extension])

django_pasttrec_manager/views/cards.py
from django.db.models import Q
from django.urls import reverse
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
import json  # , pasttrec

from ..models import Card, CardSettings, Connection, Revision, Setup, TDC
from ..forms import CardInsertForm, CardInsertMultipleForm, CardSettingsForm, CardSettingsMassChangeForm, RevisionForm
from .views import create_revision_snapshot, find_last_card_revision, IndexView

# Create your views here.


def get_card_or_top_map(c):
    if c is None:
        return None

    _c = c
    while True:
        if _c.map_to is None:
            return _c
        _c = _c.map_to


def in_map_chain(card, object):
    if card is None:
        return False

    _c = card
    while True:
        if _c == object:
            return True

        if _c.map_to is None:
            return False
        _c = _c.map_to


def card_view_lookup(request, id):
    obj = Card.objects.filter(name=id)
    if obj:
        return redirect("django_pasttrec_manager:card", obj.pk)

    obj = get_object_or_404(Card, febid=id)
    return redirect("django_pasttrec_manager:card", obj.pk)


class CardView(generic.DetailView):
    model = Card
    template_name = "django_pasttrec_manager/card_details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        card_id = self.kwargs.get("pk", None)

        cards = CardSettings.objects.filter(card=card_id).order_by("-revision__creation_on")

        context["revisions"] = cards

        return context


class CardsView(IndexView):
    template_name = "django_pasttrec_manager/cards.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cards = Card.objects.order_by("name")
        cards_and_settings = []
        for c in cards:
            cards_and_settings.append({"card": c, "num_settings": CardSettings.objects.filter(card=c.pk).count()})
        context["cards"] = cards_and_settings
        return context


def insert_card_view(request, name=None, febid=None):
    if name is not None and febid is not None:
        if request.user.is_authenticated:
            obj, created = Card.objects.update_or_create(febid=febid, name=name)
            return redirect("django_pasttrec_manager:card", obj.pk)
        else:
            return HttpResponse("Unauthorized", status=401)

    elif (name is None) is not (febid is None):
        return HttpResponse("Incorrect data", status=405)

    if request.method == "POST":
        form = CardInsertForm(request.POST)

        if form.is_valid():
            obj, created = Card.objects.update_or_create(
                febid=form.cleaned_data["febid"], name=form.cleaned_data["name"], notes=form.cleaned_data["notes"]
            )
            return redirect("django_pasttrec_manager:index")

        return render(
            request,
            "django_pasttrec_manager/insert_card.html",
            context={
                "form": form,
            },
        )

    else:
        form = CardInsertForm()
        return render(
            request,
            "django_pasttrec_manager/insert_card.html",
            context={
                "form": form,
            },
        )


def insert_cards_view(request, names=None):
    if request.method == "POST":
        form = CardInsertMultipleForm(request.POST)

        if form.is_valid():
            names = form.cleaned_data["name"].split(",")
            notes = form.cleaned_data["notes"]
            for n in names:
                obj, created = Card.objects.update_or_create(name=n, notes=notes)
            return redirect("django_pasttrec_manager:index")
        else:
            return redirect("django_pasttrec_manager:insert_cards")

    else:
        form = CardInsertMultipleForm()
        return render(
            request,
            "django_pasttrec_manager/insert_cards.html",
            context={
                "form": form,
            },
        )


def add_settings_view(request, card_pk=None, rev_pk=None):
    if request.method == "POST":
        form = CardSettingsForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("django_pasttrec_manager:card", form.cleaned_data["card"].pk)
        else:
            return redirect("django_pasttrec_manager:add_settings")

    else:
        card = Card.objects.get(pk=card_pk)
        form = CardSettingsForm(
            initial={
                "card": card_pk,
                "revision": rev_pk,
            }
        )

        form.fields["map_to"].queryset = CardSettings.objects.filter(card=card)
        return render(
            request,
            "django_pasttrec_manager/card_settings_change.html",
            context={
                "card": card,
                "form": form,
                "form_rev": RevisionForm(),
                "redirect_to": reverse("django_pasttrec_manager:add_settings_by_card", args=[card_pk]),
            },
        )


def delete_settings_view(request, card_pk=None):
    if request.method == "POST":
        try:
            card = CardSettings.objects.get(pk=card_pk)
            card_id = card.card.pk
            card.delete()
            return redirect("django_pasttrec_manager:card", card_id)

        except CardSettings.DoesNotExist:
            return redirect("django_pasttrec_manager:index")

        pass

    else:
        try:
            card = CardSettings.objects.get(pk=card_pk)
        except CardSettings.DoesNotExist:
            return redirect("django_pasttrec_manager:index")

        return render(
            request,
            "django_pasttrec_manager/card_settings_remove.html",
            context={
                "card_revision": card,
            },
        )


def change_settings_view(request, pk):
    if request.method == "POST":
        instance = get_object_or_404(CardSettings, pk=pk)
        form = CardSettingsForm(request.POST, instance=instance)

        if form.is_valid():
            form.save()
            return redirect("django_pasttrec_manager:card", form.cleaned_data["card"].pk)
        else:
            return redirect("django_pasttrec_manager:change_settings", pk)

    else:
        cs = CardSettings.objects.get(pk=pk)
        all_cs = CardSettings.objects.exclude(pk=cs.pk).filter(card=cs.card)
        qq = Q(pk=cs.pk)
        for _cs in all_cs:
            test = in_map_chain(_cs, cs)
            if test:
                qq = qq | Q(pk=_cs.pk)

        form = CardSettingsForm(instance=cs)
        form.fields["map_to"].queryset = CardSettings.objects.filter(card=cs.card).exclude(qq)
        return render(
            request,
            "django_pasttrec_manager/card_settings_change.html",
            context={
                "settings": cs,
                "form": form,
                "redirect_to": reverse("django_pasttrec_manager:change_settings", args=[pk]),
            },
        )


def get_action_dict():
    return {"before": None, "action": None, "after": None}


class Action:
    COPY = "COPY"
    UPDATE = "UPDATE"


def test_card(revision, card):
    a = get_action_dict()
    if card is None:
        return None

    if card.revision != revision:
        a["before"] = card
        a["action"] = Action.COPY
        a["after"] = "NEW"
    else:
        a["before"] = card
        a["action"] = Action.UPDATE
        if card.map_to:
            a["after"] = "NEW from map"
        else:
            a["after"] = card

    return a


def change_settings_mass_view(request, rev):
    actions = []
    # prepare actions list
    revision = Revision.objects.get(pk=rev)
    snapshot = create_revision_snapshot(revision)

    for k, v in snapshot.items():
        a = test_card(revision, v["card1"])
        if a is not None:
            actions.append(a)
        a = test_card(revision, v["card2"])
        if a is not None:
            actions.append(a)
        a = test_card(revision, v["card3"])
        if a is not None:
            actions.append(a)

    if request.method == "POST":
        form = CardSettingsMassChangeForm(request.POST)

        if form.is_valid():
            threshold = request.POST["threshold"]
            tc1c = request.POST["tc1c"]
            tc1r = request.POST["tc1r"]
            tc2c = request.POST["tc2c"]
            tc2r = request.POST["tc2r"]

            for a in actions:
                c = a["before"]

                if c.map_to is not None:
                    old_pk = c.pk
                    c = get_card_or_top_map(c.map_to)
                    c.pk = old_pk
                    c.map_to = None

                c.revision = revision

                if threshold != "":
                    c.threshold_0 = threshold
                    c.threshold_1 = threshold

                if tc1c != "":
                    c.tc1c_0 = tc1c
                    c.tc1c_1 = tc1c

                if tc1r != "":
                    c.tc1r_0 = tc1r
                    c.tc1r_1 = tc1r

                if tc2c != "":
                    c.tc2c_0 = tc2c
                    c.tc2c_1 = tc2c

                if tc2r != "":
                    c.tc2r_0 = tc2r
                    c.tc2r_1 = tc2r

                if a["action"] == Action.COPY:
                    c.pk = None

                c.save()
            # form.save()
            # return redirect('django_pasttrec_manager:card', form.cleaned_data['card'].pk)
        # else:
        # print(request.POST)
        # return render(
        # request,
        #'django_pasttrec_manager/card_settings_mass.html',
        # context = {
        #'rev' : revision,
        #'form' : form,
        #'actions' : actions
        # }
        # );
        return redirect("django_pasttrec_manager:setup", revision.setup.pk)

    else:
        form = CardSettingsMassChangeForm()
        return render(
            request,

django_pasttrec_manager/templates/django_pasttrec_manager/_revision_create.html
{% load i18n filters %}

  <div class="form-group row">
    <label class="col-2 col-form-label" for="id_setup">{{ form.setup.label_tag }}</label>
    <div class="col-10 form-inline">{{ form.setup|addclass:"custom-select w-25" }}</div>
  </div>

  <div class="form-group row">
    <label class="col-2 col-form-label" for="id_creation_on">{{ form.creation_on.label_tag }}</label>
    <div class="col-10 form-inline">
    {{ form.creation_on|adddtclass:'vDateField ce-dtdate form-control w-25;vTimeField ce-dttime form-control w-25 ml-2' }}{{ form.creation_on.errors }}
    </div>
  </div>

  {% if redirect_to %}
  <input type="hidden" name="redirect_to" value="{{ redirect_to }}" />
  {% endif %}

  <div>
    <input class="btn" type="submit" value="{% trans 'Create' %}" />
    <input class="btn btn-danger" type="reset" value="{% trans 'Clear' %}" />
  </div>

django_pasttrec_manager/templates/django_pasttrec_manager/add_cards_setup.html
{% extends 'django_pasttrec_manager/base.html' %}
{% load i18n filters %}

{% block content %}
<div class="container">

<div class="row">
<div class="col">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'passtrec_trb3setup:index' %}">Home</a></li>
    <li class="breadcrumb-item active" >{{ setup.name }}</li>
  </ol>
</nav>

{% if form %}
<h3>Insert Card Setup</h3>

<form action="{% url 'django_pasttrec_manager:add_cards_setup' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.non_field_errors }}
  {{ form }}
  <div>
    <input class="btn" type="submit" value="{% trans 'Insert' %}" />
  </div>
</form>
{% endif %}

</div>
</div>

</div>
{% endblock %}

django_pasttrec_manager/templates/django_pasttrec_manager/calibration_json_upload.html
{% extends 'django_pasttrec_manager/base.html' %}
{% load i18n filters mathfilters %}

{% block head_extra %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
<div class="container">

<div class="row">
<div class="col">

<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'passtrec_trb3setup:index' %}">Home</a></li>
    <li class="breadcrumb-item active" >{{ setup.name }}</li>
  </ol>
</nav>

<!-- WIZZARD -->

<div class="progress">
  <div class="progress-bar bg-warning" role="progressbar" style="width: {{ 100.0|div:wizard.steps.count|mul:wizard.steps.step1 }}%;" aria-valuenow="{{ wizard.steps.step1 }}" aria-valuemin="0" aria-valuemax="{{ wizard.steps.count }}"></div>
</div>

<p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }} : Upload json file</p>
<form action="{% url 'django_pasttrec_manager:import_calibrations_wizard' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
  {{ wizard.management_form }}

  {{ wizard.form.non_field_errors }}
  <table class="table">
    <tr><th>{{ wizard.form.file.label_tag }}</th>
    <td>{{ wizard.form.file }}{{ wizard.form.creation_on.errors }}</td></tr>
  </table>

  </table>
  {% if wizard.steps.prev %}
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
  <button name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}">{% trans "prev step" %}</button>
  {% endif %}
  <div>
    <input class="btn btn-success" type="submit" value="{% trans 'Upload' %}" />
    <input class="btn btn-danger" type="reset" value="{% trans 'Clear' %}" />
  </div>
</form>
<!-- WIZZARD -->

</div>
</div>

</div>
{% endblock %}

django_pasttrec_manager/templates/django_pasttrec_manager/card.html
{% extends 'django_pasttrec_manager/base.html' %}
{% load filters %}

{% block content %}
<div class="container">

<div class="row">
<div class="col">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'passtrec_trb3setup:index' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'passtrec_trb3setup:cards' %}">Cards</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>
  </ol>
</nav>
</div>
</div>

<div class="card border-dark mb-3">
  <div class="card-header">Card details</div>
  <div class="card-body text-dark">
  {% include 'django_pasttrec_manager/widgets/card_widget.html' with data=object %}
  </div>
</div>

<div class="row">

<div class="col-10">
  {% if calibrations %}
  {% for c in calibrations %}
  <div class="card border-dark mb-3">
    <div class="card-header">Calibration details for <a href="{% url 'django_pasttrec_manager:configuration' c.config.pk %}"><span class="badge text-bg-primary">{{ c.config.name }}</span></a> configuration</div>

    <div class="card-body text-dark">
    {% include 'django_pasttrec_manager/widgets/asic_configuration_noname_widget.html' with data=c.config %}
    <hr>
    <div class="row">
    {% include "django_pasttrec_manager/widgets/asic_baseline_inline_widget.html" with asic_no=0 data=c.asic0 %}
    </div>
    <div class="row">
    {% include "django_pasttrec_manager/widgets/asic_baseline_inline_widget.html" with asic_no=1 data=c.asic1 %}
    </div>

    </div>
  </div>
  {% endfor %}
  {% else %}
  <p>No Card Settings are available.</p>
{% endif %}
</div>

<div class="col-2">
  <div class="card border-dark mb-3">
    <div class="card-header">Cards Setups</div>
    <div class="card-body text-dark">
    {% if cards_setups %}
    {% for cs in cards_setups %}
    <a class="btn btn-outline-dark btn-sm w-100" href="{% url 'django_pasttrec_manager:cards_setup' cs.pk %}">{{ cs.name }}</a>
    {% endfor %}
    {% else %}
    <p>Not present in any setup.</p>
    {% endif %}
    </div>
  </div>
</div>

</div>

</div>
{% endblock %}

django_pasttrec_manager/templates/django_pasttrec_manager/index.html
{% extends 'django_pasttrec_manager/base.html' %}

{% load bootstrap_icons %}

{% block content %}
<div class="container">

<div class="row">
<div class="col">
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>
</div>
</div>

{% if messages %}
<h3>Messages</h3>
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

<div class="row">
<div class="col-3">

<div class="card mb-3">
  <div class="card-header">
    Select configuration
  </div>
  <div class="card-body">
    {% if configurations %}
    <nav class="nav flex-column">
    {% for config in configurations %}
      <a class="nav-link" href="{% url 'django_pasttrec_manager:configuration' config.id %}">{{ config.name }}</a>
    {% endfor %}
    </nav>
    {% else %}
    <p>No configurations are available.</p>
    {% endif %}
  </div>
  <div class="card-footer text-muted">

    <nav class="nav">
      <a class="nav-link" href="{% url 'django_pasttrec_manager:import_calibrations_wizard' %}">
        {% bs_icon 'file-arrow-down' %} Import calibrations from file
      </a>
      <a class="nav-link" href="{% url 'django_pasttrec_manager:export_calibration_wizard' %}">
        {% bs_icon 'file-arrow-up' %} Export calibrations to file
      </a>
    </nav>

  </div>
</div>

<div class="card mb-3">
  <div class="card-header">
    Select cards setup
  </div>
  <div class="card-body">
    {% if cards_setups %}
    <nav class="nav flex-column">
      {% for cs in cards_setups %}
      <a class="nav-link" href="{% url 'django_pasttrec_manager:cards_setup' cs.id %}">{{ cs.name }}</a>
    {% endfor %}
    </nav>
    {% else %}
    <p>No card setups are available.</p>
    {% endif %}
  </div>
  <div class="card-footer text-muted">

  <nav class="nav">
    <a class="nav-link" href="{% url 'django_pasttrec_manager:add_cards_setup' %}">
    {% bs_icon 'folder-plus' %} Add new cards setup
    </a>
    <a class="nav-link" href="{% url 'django_pasttrec_manager:import_cards_setups_wizard' %}">
    {% bs_icon 'folder-plus' %} Import new cards setup
    </a>
  </nav>

  </div>
</div>

</div>

<div class="col">

<div class="card mb-3">
  <div class="card-header">
    List of cards

    <!-- Filter input -->
    <div class="float-sm-end">
      <div class="hstack gap-3">
        <nav class="nav">
          <a class="nav-link" href="{% url 'django_pasttrec_manager:cards' %}">
          {% bs_icon 'collection' %} View detailed list
          </a>
        </nav>
        <input class="form-control-sm" id="card_search_input_field" type="text" placeholder="Cards filter"
          style="padding: 0 .5rem 0 .5rem; min-height: 0;"
          type       = "text"
          onchange   = "filter_cards();"
          onkeypress = "this.onchange();"
          onpaste    = "this.onchange();"
          oninput    = "this.onchange();">
      </div>
    </div>
    <!-- END: Filter input -->

  </div>

  <div class="card-body" id="cards-container">
  {% if cards %}
  <div class="">
  {% for card in cards %}
    <span class="dummy-filter-card">
    <a class="btn btn-outline-dark btn-sm" href="{% url 'django_pasttrec_manager:card' card.id %}">{{ card.name }}</a>
    </span>
  {% endfor %}
  </div>
  {% else %}
    <p>No cards are available.</p>
  {% endif %}
  </div>
  <div class="card-footer text-muted">
    <nav class="nav">
      <a class="nav-link" href="{% url 'django_pasttrec_manager:cards' %}">
      {% bs_icon 'collection' %} View detailed list
      </a>
    </nav>
  </div>
</div>

</div>
</div>

<script>
function filter_cards(){
  // Declare variables
  var input, filter, table, tr, td, i;
  input = document.getElementById("card_search_input_field");
  filter = input.value.toUpperCase();
  table = document.getElementById("cards-container");
  tr = table.getElementsByClassName("dummy-filter-card");

  console.log(tr.length)

  // Loop through all table rows, and hide those who don't match the search query
  for (i = 0; i < tr.length; i++) {
    td = tr[i].getElementsByTagName("a") ;
    for(j=0 ; j<td.length ; j++)
    {
      let tdata = td[j] ;
      if (tdata) {
        if (tdata.innerHTML.toUpperCase().indexOf(filter) > -1) {
          tr[i].style.display = "";
          break ;
        } else {
          tr[i].style.display = "none";
        }
      }
    }
  }
}
</script>
</div>
{% endblock %}